shared:
  box: oraclebase/oracle-8
  non_rotational: 'on'
  asm_crs_disk_1: "K:/asm/ol8_19_rac/asm_crs_disk_1.vdi"
  asm_crs_disk_2: "K:/asm/ol8_19_rac/asm_crs_disk_2.vdi"
  asm_crs_disk_3: "K:/asm/ol8_19_rac/asm_crs_disk_3.vdi"
  asm_crs_disk_size: 2
  asm_data_disk_1: "K:/asm/ol8_19_rac/asm_data_disk_1.vdi"
  asm_data_disk_size: 40
  asm_reco_disk_1: "K:/asm/ol8_19_rac/asm_reco_disk_1.vdi"
  asm_reco_disk_size: 20

dns:
  vm_name: ol8_19_dns
  mem_size: 1024
  cpus: 1
  public_ip: 192.168.56.100

node1:
  vm_name: ol8_19_rac1
  mem_size: 10240
  cpus: 4
  public_ip: 192.168.56.101
  private_ip: 192.168.51.101
  u01_disk: "K:/asm/ol8_19_rac/ol8_19_rac1_u01.vdi"

node2:
  vm_name: ol8_19_rac2
  mem_size: 10240
  cpus: 4
  public_ip: 192.168.56.102
  private_ip: 192.168.51.102
  u01_disk: "K:/asm/ol8_19_rac/ol8_19_rac2_u01.vdi"
