VAGRANTFILE_API_VERSION = "2"
NAME = "win95"

Vagrant.configure("2") do |config|
  config.vm.box = "amitpatole/vagrant-windows-3.1"
  config.vm.box_version = "0.0.1"
  config.vm.define NAME

  config.vm.provider "virtualbox" do |v|
#     v.memory = 248
     v.name = NAME
  end

  # VM hostname
  config.vm.hostname = NAME
  config.vm.box_check_update = false
end
