box: oraclebase/oracle-8
vm_name: ol8_19_vagrant
mem_size: 4096
cpus: 4
public_ip: 192.168.56.140
disk1_name: "F:/vm/ol8_19/ol8_19_u01.vdi"
disk2_name: "F:/vm/ol8_19/ol8_19_u02.vdi"
non_rotational: 'on'
disk_size: 100
